services: 
  jupyter-notebook:
    image:  quandothoang/dsci522-dockerfile-practice:3164872
    ports:
      - "8787:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
