name: 522_proj
channels:
  - conda-forge
dependencies:
  - python=3.11.10
  - numpy=1.26.4
  - scipy=1.16.3
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - ipykernel=7.1.0
  - jupyterlab      
  - altair=6.0.0
  - vl-convert-python=1.8.0
  - wordcloud=1.9.4
  - matplotlib=3.9.2
  - vadersentiment=3.3.2
  - nltk=3.9.2
  - seaborn=0.13.2
  - pandera=0.26.1
  - click=8.1.7
  - quarto=1.6.40
  - requests=2.32.3
  - pip
  - pip:
      - deepchecks==0.18.1
