name: 522_proj
channels:
  - conda-forge
dependencies:
  - python=3.12
  - conda-lock=3.0.4
  - scipy=1.16.3
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - ipykernel=7.1.0
  - altair=6.0.0
  - wordcloud=1.9.4
  - matplotlib=3.10.8
  - vadersentiment=3.3.2
  - nltk=3.9.2

